# Generated by Django 3.2.7 on 2021-10-04 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='Jogo_Data',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
