# Generated by Django 3.2.7 on 2021-10-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogos', '0002_alter_jogo_jogo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='Jogo_Data',
            field=models.CharField(max_length=30, verbose_name='%d/%m/%Y %H:%M'),
        ),
    ]
