# Generated by Django 3.2.7 on 2021-10-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogos', '0003_alter_jogo_jogo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='Jogo_Data',
            field=models.DateField(),
        ),
    ]
