# Generated by Django 3.2.7 on 2021-10-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campo_Nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('Campo_End', models.CharField(max_length=100, verbose_name='Endereco')),
                ('Campo_Maps', models.CharField(max_length=200, verbose_name='Link_Maps')),
            ],
        ),
    ]
