# Generated by Django 3.2.7 on 2021-09-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Juiz_Nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
    ]
