# Generated by Django 3.2.7 on 2021-09-28 05:09

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('User_Email', models.CharField(max_length=60, verbose_name='Email')),
                ('User_Senha', models.CharField(max_length=20, verbose_name='Senha')),
                ('User_Cel', models.CharField(max_length=15, verbose_name='Celular')),
                ('User_Imagem', stdimage.models.StdImageField(upload_to='usuarios', verbose_name='imagem')),
            ],
        ),
    ]
