# Generated by Django 3.2.7 on 2021-10-05 13:59

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuario_user_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='User_Imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='usuarios', verbose_name='imagem'),
        ),
    ]
