# Generated by Django 3.2.7 on 2021-09-28 05:09

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_Nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('Time_Pontos', models.IntegerField(verbose_name='Pontos')),
                ('Time_Vitorias', models.IntegerField(verbose_name='Vitorias')),
                ('Time_Empates', models.IntegerField(verbose_name='Empates')),
                ('Time_Derrotas', models.IntegerField(verbose_name='Derrotas')),
                ('Time_SaldoGols', models.IntegerField(verbose_name='SG')),
                ('Time_GolsFeitos', models.IntegerField(verbose_name='GF')),
                ('Time_GolsSofridos', models.IntegerField(verbose_name='GS')),
                ('Time_Treinador', models.CharField(max_length=30, verbose_name='Treinador')),
                ('Time_Imagem', stdimage.models.StdImageField(upload_to='times', verbose_name='imagem')),
            ],
        ),
    ]
