# Generated by Django 3.2.7 on 2021-10-05 13:59

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Times', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='Time_Imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='times', verbose_name='imagem'),
        ),
    ]
